name: rechnungshof

services:
    api:
        container_name: rechnungshof_backend
        extends:
            file: docker-compose.base.yaml
            service: api
        image: quay.io/abrechnung/api:latest-release

    frontend:
        container_name: rechnungshof_frontend
        image: quay.io/abrechnung/frontend:latest-release
        depends_on:
            api:
                condition: service_healthy

    cron:
        container_name: rechnungshof_cron
        extends:
            file: docker-compose.base.yaml
            service: cron
        image: quay.io/abrechnung/api:latest-release
